heat_template_version: rocky

parameters:
  RHELImage:
    type: string
    default: RHEL-8.4.0-x86_64-latest
  DirectorUsername:
    type: string
    default: stack
  ControllerCount:
    type: number
    default: 3
  ComputeCount:
    type: number
    default: 1
  ControllerFlavor:
    type: string
    default: m1.large
  ComputeFlavor:
    type: string
    default: m1.medium
  DirectorFlavor:
    type: string
    default: m1.xlarge
  KeyName:
    type: string
    default: jslagle
  FloatingNetwork:
    type: string
    default: provider_net_sysops
  RunFullDeploy:
    type: boolean
    default: false
    description: |
      Run the full deployment script (/home/stack/deploy.sh) automatically as
      part of cloud-init. Will deploy undercloud and overcloud. Defaults to
      False.

resources:

  CtlplaneNetwork:
    type: OS::Neutron::Net
    properties:
      name:
        list_join:
          - '-'
          - - {get_param: OS::stack_name}
            - ctlplane
      port_security_enabled: false

  ManagementNetwork:
    type: OS::Neutron::Net
    properties:
      name:
        list_join:
          - '-'
          - - {get_param: OS::stack_name}
            - management
      port_security_enabled: false

  CtlplaneSubnet:
    type: OS::Neutron::Subnet
    properties:
      network: {get_resource: CtlplaneNetwork}
      allocation_pools:
        - start: 192.168.24.1
          end: 192.168.24.200
      cidr: 192.168.24.0/24
      enable_dhcp: false
      gateway_ip: null

  ManagementSubnet:
    type: OS::Neutron::Subnet
    properties:
      network: {get_resource: ManagementNetwork}
      allocation_pools:
        - start: 10.98.0.2
          end: 10.98.0.200
      enable_dhcp: true
      cidr: 10.98.0.0/24

  FloatingRouter:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: {get_param: FloatingNetwork}
      name:
        list_join:
          - '-'
          - - {get_param: OS::stack_name}
            - router

  FloatingRouterInterface:
    type: OS::Neutron::RouterInterface
    properties:
      router: {get_resource: FloatingRouter}
      subnet: {get_resource: ManagementSubnet}

  Director:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: DirectorFlavor}
      key_name: {get_param: KeyName}
      name: osp17-director
      image: {get_param: RHELImage}
      networks:
        - port: {get_resource: ManagementPort}
        - port: {get_resource: CtlplanePort}
      user_data: {get_resource: DirectorUserData}
      user_data_format: RAW

  DirectorServerUserData:
    type: server-user-data.yaml

  DirectorTripleOClientConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/usr/bin/bash
        sudo dnf -y install python3-tripleoclient
        # Needed so the undercloud install doesn't fail fqdn validation
        sudo hostnamectl set-hostname osp17-director.localdomain

  DirectorUndercloudConfig:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
          # We can't use owner:stack here b/c write_files runs before users
          # See https://bugs.launchpad.net/cloud-init/+bug/1486113
          - path: /home/stack/undercloud.conf
            permissions: '0644'
            content: {get_file: undercloud.conf}
          - path: /home/stack/container-image-prepare.yaml
            permissions: '0644'
            content: {get_file: container-image-prepare.yaml}
          - path: /home/stack/vip-data-default.yaml
            permissions: '0644'
            content: {get_file: vip-data-default.yaml}
          - path: /home/stack/overcloud-environment.yaml
            permissions: '0644'
            content: {get_file: overcloud-environment.yaml}
          - path: /home/stack/net_config_static_bridge.j2
            permissions: '0644'
            content: {get_file: net_config_static_bridge.j2}
          - path: /home/stack/01-undercloud-install.sh
            permissions: '0755'
            content: {get_file: 01-undercloud-install.sh}
          - path: /home/stack/02-network-provision.sh
            permissions: '0755'
            content: {get_file: 02-network-provision.sh}
          - path: /home/stack/03-vip-provision.sh
            permissions: '0755'
            content: {get_file: 03-vip-provision.sh}
          - path: /home/stack/04-node-provision.sh
            permissions: '0755'
            content: {get_file: 04-node-provision.sh}
          - path: /home/stack/05-overcloud-deploy.sh
            permissions: '0755'
            content: {get_file: 05-overcloud-deploy.sh}
          - path: /home/stack/deploy.sh
            permissions: '0755'
            content: {get_file: deploy.sh}
          - path: /home/stack/overcloud-baremetal-deploy.yaml
            permissions: '0644'
            content:
              str_replace:
                template: "value"
                params:
                  value: {get_attr: [BaremetalDeployInput, value]}

  DirectorRunFullDeploy:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        if:
          - {get_param: RunFullDeploy}
          - |
            #!/bin/bash
            sudo -iu stack /bin/bash -c "SUDO_USER='stack' /home/stack/deploy.sh"
          - |
            #!/bin/bash
            true

  DirectorUserData:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        list_concat:
          - {get_attr: [DirectorServerUserData, ServerUserData]}
          - - config: {get_resource: DirectorTripleOClientConfig}
              subtype: x-shellscript
            - config: {get_resource: DirectorUndercloudConfig}
            - config: {get_resource: DirectorRunFullDeploy}
              subtype: x-shellscript

  BaremetalDeployInput:
    type: OS::Heat::Value
    properties:
      value:
        - name: Controller
          count: {get_param: ControllerCount}
          defaults:
            managed: false
            networks:
              - network: ctlplane
            network_config:
              template: /usr/share/ansible/roles/tripleo_network_config/templates/net_config_static_bridge.j2
          instances: {get_attr: [Controllers, BaremetalDeployInput]}
        - name: Compute
          count: {get_param: ComputeCount}
          defaults:
            managed: false
            networks:
              - network: ctlplane
            network_config:
              template: /usr/share/ansible/roles/tripleo_network_config/templates/net_config_static_bridge.j2
          instances: {get_attr: [Computes, BaremetalDeployInput]}

  ManagementPort:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: ManagementNetwork}
      fixed_ips:
        - ip_address: 10.98.0.5

  CtlplanePort:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: CtlplaneNetwork}
      fixed_ips:
        - ip_address: 192.168.24.1

  # Not actually associated with the Director server, resource is just here to
  # reserve the IP so the undercloud install can use it.
  DirectorAdminVip:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: CtlplaneNetwork}
      fixed_ips:
        - ip_address: 192.168.24.3

  # Not actually associated with the Director server, resource is just here to
  # reserve the IP so the undercloud install can use it.
  DirectorPublicVip:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: CtlplaneNetwork}
      fixed_ips:
        - ip_address: 192.168.24.2

  DirectorFloatingIP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: FloatingNetwork}

  DirectorFloatingIpAssociation:
    type: OS::Neutron::FloatingIPAssociation
    depends_on: FloatingRouterInterface
    properties:
      floatingip_id: {get_resource: DirectorFloatingIP}
      port_id: {get_resource: ManagementPort}

  Controllers:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: ControllerCount}
      resource_def:
        type: overcloud-server.yaml
        properties:
          flavor: {get_param: ControllerFlavor}
          key_name: {get_param: KeyName}
          name:
            list_join:
              - '-'
              - - {get_param: OS::stack_name}
                - 'controller'
                - '%index%'
          image: {get_param: RHELImage}
          index: |
            %index%
          SubnetStart: 10
          ManagementNetwork: {get_resource: ManagementNetwork}
          CtlplaneNetwork: {get_resource: CtlplaneNetwork}

  Computes:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: ComputeCount}
      resource_def:
        type: overcloud-server.yaml
        properties:
          flavor: {get_param: ComputeFlavor}
          key_name: {get_param: KeyName}
          name:
            list_join:
              - '-'
              - - {get_param: OS::stack_name}
                - 'compute'
                - '%index%'
          image: {get_param: RHELImage}
          index: |
            %index%
          SubnetStart: 100
          ManagementNetwork: {get_resource: ManagementNetwork}
          CtlplaneNetwork: {get_resource: CtlplaneNetwork}

outputs:
  DirectorFloatingIP:
    description: DirectorFloatingIP
    value: {get_attr: [DirectorFloatingIP, floating_ip_address]}
