heat_template_version: rocky

parameters:
  image:
    type: string
  flavor:
    type: string
  key_name:
    type: string
  name:
    type: string
  index:
    type: number
  SubnetStart:
    type: number
  ManagementNetwork:
    type: string
  DeployNetwork:
    type: string

resources:

  CephStorageServer:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      key_name: {get_param: key_name}
      name: {get_param: name}
      image: {get_param: image}
      networks:
        - network: {get_param: ManagementNetwork}
          fixed_ip: {get_attr: [ManagementIP, value]}
        - network: {get_param: DeployNetwork}
          fixed_ip: {get_attr: [CtlplaneIP, value]}
        - network: {get_param: DeployNetwork}
          fixed_ip: {get_attr: [StorageIP, value]}
        - network: {get_param: DeployNetwork}
          fixed_ip: {get_attr: [StorageMgmtIP, value]}
        - network: {get_param: DeployNetwork}
          fixed_ip: {get_attr: [ExternalIP, value]}
      user_data: {get_resource: OvercloudUserData}
      user_data_format: SOFTWARE_CONFIG

  ManagementIP:
    type: OS::Heat::Value
    properties:
      value:
        str_replace:
          template: 10.98.0.<%ip%>
          params:
            <%ip%>:
              yaql:
                expression: $.data.ip_base + $.data.index
                data:
                  ip_base: {get_param: SubnetStart}
                  index: {get_param: index}

  CtlplaneIP:
    type: OS::Heat::Value
    properties:
      value:
        str_replace:
          template: 192.168.24.<%ip%>
          params:
            <%ip%>:
              yaql:
                expression: $.data.ip_base + $.data.index
                data:
                  ip_base: {get_param: SubnetStart}
                  index: {get_param: index}

  StorageIP:
    type: OS::Heat::Value
    properties:
      value:
        str_replace:
          template: 172.16.1.<%ip%>
          params:
            <%ip%>:
              yaql:
                expression: $.data.ip_base + $.data.index
                data:
                  ip_base: {get_param: SubnetStart}
                  index: {get_param: index}

  StorageMgmtIP:
    type: OS::Heat::Value
    properties:
      value:
        str_replace:
          template: 172.16.3.<%ip%>
          params:
            <%ip%>:
              yaql:
                expression: $.data.ip_base + $.data.index
                data:
                  ip_base: {get_param: SubnetStart}
                  index: {get_param: index}

  InternalApiIP:
    type: OS::Heat::Value
    properties:
      value:
        str_replace:
          template: 172.16.2.<%ip%>
          params:
            <%ip%>:
              yaql:
                expression: $.data.ip_base + $.data.index
                data:
                  ip_base: {get_param: SubnetStart}
                  index: {get_param: index}

  TenantIP:
    type: OS::Heat::Value
    properties:
      value:
        str_replace:
          template: 172.16.0.<%ip%>
          params:
            <%ip%>:
              yaql:
                expression: $.data.ip_base + $.data.index
                data:
                  ip_base: {get_param: SubnetStart}
                  index: {get_param: index}

  ExternalIP:
    type: OS::Heat::Value
    properties:
      value:
        str_replace:
          template: 10.0.0.<%ip%>
          params:
            <%ip%>:
              yaql:
                expression: $.data.ip_base + $.data.index
                data:
                  ip_base: {get_param: SubnetStart}
                  index: {get_param: index}

  CephStorageServerUserData:
    type: server-user-data.yaml

  OvercloudOsNetConfigUserData:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/usr/bin/bash
        sudo dnf -y install os-net-config openvswitch lvm2 jq

  OvercloudUserData:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        list_concat:
          - {get_attr: [CephStorageServerUserData, ServerUserData]}
          - - config: {get_resource: OvercloudOsNetConfigUserData}
              subtype: x-shellscript

  CephVolumes:
    type: OS::Cinder::Volume
    properties:
      size: 60

  CephVolumesAttachment:
    type: OS::Cinder::VolumeAttachment
    depends_on: CephStorageServer
    properties:
      volume_id: { get_resource: CephVolumes }
      instance_uuid: { get_resource: CephStorageServer }
      mountpoint: /dev/sdb

outputs:
  OS::stack_id:
    description: OS::stack_id
    value: {get_resource: CephStorageServer}
  name:
    description: name
    value: {get_attr: [CephStorageServer, name]}
  BaremetalDeployInput:
    description: BaremetalDeployInput
    value:
      hostname: {get_attr: [CephStorageServer, name]}
      name: {get_attr: [CephStorageServer, name]}
      networks:
        - network: ctlplane
          fixed_ip: {get_attr: [CtlplaneIP, value]}
        - network: storage
          fixed_ip: {get_attr: [StorageIP, value]}
        - network: storage_mgmt
          fixed_ip: {get_attr: [StorageMgmtIP, value]}
        - network: external
          fixed_ip: {get_attr: [ExternalIP, value]}
