heat_template_version: rocky

parameters:
  image:
    type: string
  flavor:
    type: string
  key_name:
    type: string
  name:
    type: string
  index:
    type: number
  SubnetStart:
    type: number
  ManagementNetwork:
    type: string
  CtlplaneNetwork:
    type: string

resources:

  OvercloudServer:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      key_name: {get_param: key_name}
      name: {get_param: name}
      image: {get_param: image}
      networks:
        - network: {get_param: ManagementNetwork}
          fixed_ip: {get_attr: [ManagementIP, value]}
        - network: {get_param: CtlplaneNetwork}
          fixed_ip: {get_attr: [CtlplaneIP, value]}
      user_data: {get_resource: OvercloudUserData}
      user_data_format: SOFTWARE_CONFIG

  ManagementIP:
    type: OS::Heat::Value
    properties:
      value:
        str_replace:
          template: 10.98.0.<%ip%>
          params:
            <%ip%>:
              yaql:
                expression: $.data.ip_base + $.data.index
                data:
                  ip_base: {get_param: SubnetStart}
                  index: {get_param: index}

  CtlplaneIP:
    type: OS::Heat::Value
    properties:
      value:
        str_replace:
          template: 192.168.24.<%ip%>
          params:
            <%ip%>:
              yaql:
                expression: $.data.ip_base + $.data.index
                data:
                  ip_base: {get_param: SubnetStart}
                  index: {get_param: index}

  OvercloudServerUserData:
    type: server-user-data.yaml

  OvercloudOsNetConfigUserData:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/usr/bin/bash
        sudo dnf -y install os-net-config openvswitch

  OvercloudUserData:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        list_concat:
          - {get_attr: [OvercloudServerUserData, ServerUserData]}
          - - config: {get_resource: OvercloudOsNetConfigUserData}
              subtype: x-shellscript

outputs:
  OS::stack_id:
    description: OS::stack_id
    value: {get_resource: OvercloudServer}
  name:
    description: name
    value: {get_attr: [OvercloudServer, name]}
  BaremetalDeployInput:
    description: BaremetalDeployInput
    value:
      hostname: {get_attr: [OvercloudServer, name]}
      name: {get_attr: [OvercloudServer, name]}
      networks:
        - network: ctlplane
          fixed_ip: {get_attr: [CtlplaneIP, value]}
